---
# Source: bootcamp-api/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bootcamp-api-secret
type: Opaque
stringData:
  API_KEY: "change-me-in-part-4"
---
# Source: bootcamp-api/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootcamp-api-config
data:
  LOG_LEVEL: "info"
---
# Source: bootcamp-api/templates/service-canary.yaml
apiVersion: v1
kind: Service
metadata:
  name: bootcamp-api-canary
  namespace: bootcamp
spec:
  type: ClusterIP
  ports: [{ port: 80, targetPort: http, name: http }]
  selector:
    app.kubernetes.io/name: bootcamp-api
---
# Source: bootcamp-api/templates/service-stable.yaml
apiVersion: v1
kind: Service
metadata:
  name: bootcamp-api
  namespace: bootcamp
spec:
  type: ClusterIP
  ports: [{ port: 80, targetPort: http, name: http }]
  selector:
    app.kubernetes.io/name: bootcamp-api
---
# Source: bootcamp-api/templates/service-worker-active.yaml
apiVersion: v1
kind: Service

metadata:
  name: bootcamp-worker-active
  namespace: bootcamp

spec:
  selector:
    app: bootcamp-worker

  ports:
    - port: 80
      targetPort: 80
---
# Source: bootcamp-api/templates/service-worker-preview.yaml
apiVersion: v1
kind: Service

metadata:
  name: bootcamp-worker-preview
  namespace: bootcamp

spec:
  selector:
    app: bootcamp-worker

  ports:
    - port: 80
      targetPort: 80
---
# Source: bootcamp-api/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bootcamp-api
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: bootcamp-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# Source: bootcamp-api/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootcamp-api
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bootcamp-api
                port:
                  name: use-annotation
---
# Source: bootcamp-api/templates/analysis-db-migration.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate

metadata:
  name: db-migration-ok
  namespace: bootcamp

spec:
  metrics:
    - name: migration-check

      successCondition: result == 'ok'

      provider:
        job:
          spec:
            backoffLimit: 0

            template:
              spec:
                restartPolicy: Never

                containers:
                  - name: check
                    image: busybox

                    command:
                      - /bin/sh
                      - -c
                      - |
                        echo ok
---
# Source: bootcamp-api/templates/analysis-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: bootcamp-api-canary-health
  namespace: bootcamp
spec:
  args:
    - name: service-name
      value: bootcamp-api-canary
    - name: namespace
      value: bootcamp
  metrics:
    - name: http-5xx-rate
      interval: 30s
      count: 5
      successCondition: result[0] < 0.01     # under 1% error rate
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(
              http_requests_total{
                namespace="{{args.namespace}}",
                service="{{args.service-name}}",
                status=~"5.."
              }[1m]
            ))
            /
            sum(rate(
              http_requests_total{
                namespace="{{args.namespace}}",
                service="{{args.service-name}}",
              }[1m]
            ))
    - name: p95-latency-ms
      interval: 30s
      count: 5
      successCondition: result[0] < 400      # p95 under 400ms
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.95,
              sum(rate(
                http_request_duration_seconds_bucket{
                  namespace="{{args.namespace}}",
                  service="{{args.service-name}}",
                }[1m]
              )) by (le)
            ) * 1000
---
# Source: bootcamp-api/templates/rollout-worker.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: bootcamp-worker
  namespace: bootcamp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: bootcamp-worker

  strategy:
    blueGreen:
      activeService: bootcamp-worker-active
      previewService: bootcamp-worker-preview

      autoPromotionEnabled: false

      scaleDownDelaySeconds: 600

      prePromotionAnalysis:
        templates:
          - templateName: db-migration-ok

  template:
    metadata:
      labels:
        app: bootcamp-worker

    spec:
      containers:
        - name: worker
          image: nginx:stable

          ports:
            - containerPort: 80
---
# Source: bootcamp-api/templates/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bootcamp-api
  namespace: bootcamp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: bootcamp-api
  strategy:
    canary:
      canaryService: bootcamp-api-canary
      stableService: bootcamp-api
      trafficRouting:
        alb:
          ingress: bootcamp-api
          servicePort: 80
          rootService: bootcamp-api
      steps:
        - setWeight: 10
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: bootcamp-api-canary-health
        - setWeight: 25
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: bootcamp-api-canary-health
        - setWeight: 50
        - pause: { duration: 5m }
        - analysis:
            templates:
              - templateName: bootcamp-api-canary-health
        - setWeight: 75
        - pause: { duration: 2m }
        - setWeight: 100
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bootcamp-api
    spec:
      containers:
        - name: bootcamp-api
          image: "711387135481.dkr.ecr.us-east-1.amazonaws.com/bootcamp-api:day12-v2"
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet: { path: /health, port: http }
            periodSeconds: 5
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits:   { cpu: 500m, memory: 512Mi }
---
# Source: bootcamp-api/templates/servicemonitor-canary.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bootcamp-api-canary
  namespace: bootcamp
  labels:
    release: kps

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bootcamp-api

  namespaceSelector:
    matchNames:
      - bootcamp

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
# Source: bootcamp-api/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bootcamp-api
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bootcamp-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
