replicaCount: 2

image:
  repository: 711387135481.dkr.ecr.us-east-1.amazonaws.com/bootcamp-rtito-day15-api
  tag: day15-base
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  APP_ENV: dev

config:
  LOG_LEVEL: info

secrets:
  API_KEY: "change-me-in-part-4"

ingress:
  enabled: true

metrics:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
