apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate

metadata:
  name: db-migration-ok
  namespace: bootcamp

spec:
  metrics:
    - name: migration-check

      successCondition: result == 'ok'

      provider:
        job:
          spec:
            backoffLimit: 0

            template:
              spec:
                restartPolicy: Never

                containers:
                  - name: check
                    image: busybox

                    command:
                      - /bin/sh
                      - -c
                      - |
                        echo ok
