apiVersion: v1
kind: Service
metadata:
  name: bootcamp-api
  namespace: bootcamp
spec:
  type: ClusterIP
  ports: [{ port: 80, targetPort: http, name: http }]
  selector:
    app.kubernetes.io/name: bootcamp-api
