apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bootcamp-api-canary
  namespace: bootcamp
  labels:
    release: kps

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bootcamp-api

  namespaceSelector:
    matchNames:
      - bootcamp

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
